Repository terraform-ibm-modules/terraform-ibm-toolkit-vpc, pull requests merged in 2021-05, with the labels that each got.

#25 Adds dependency on cos_bucket for flow_log_cos_bucket_name
  main.tf
  module.yaml
  test/stages/stage3-vpc-flow-log.tf
  variables.tf
Labels: chore, patch

#28 Fixes handling of address_prefixes
  main.tf
  outputs.tf
Labels: bug, patch

#29 Updates number of elements for vpc_zone_names local variable
  main.tf
Labels: bug, patch

#30 Adds names, ids, and count to output
  outputs.tf
Labels: enhancement, patch

#34 Adds test for security groups to verify process
  .github/scripts/validate-deploy.sh
Labels: chore, patch

#35 Fixes test to validate security group rules
  .github/scripts/validate-deploy.sh
  main.tf
  outputs.tf
Labels: chore, patch

#36 Sets up the default network access control list
  main.tf
  scripts/setup-default-acl.sh
Labels: feature, minor

#37 Adds addresses to output
  outputs.tf
Labels: enhancement, patch

#40 Uses new is_default flag for addresses_prefixes
  README.md
  main.tf
  outputs.tf
  version.tf
Labels: chore, patch

#39 Fix delete acl
  scripts/setup-default-acl.sh
Labels: bug, patch

#42 Updates default security group rules for ROKS deploy
  main.tf
Labels: bug, patch
